/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_memory_MemoryUsageNative */

#ifndef _Included_com_example_memory_MemoryUsageNative
#define _Included_com_example_memory_MemoryUsageNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_memory_MemoryUsageNative
 * Method:    getMemoryUsage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_memory_MemoryUsageNative_getMemoryUsage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
