/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cpu_CpuUsageNative */

#ifndef _Included_com_example_cpu_CpuUsageNative
#define _Included_com_example_cpu_CpuUsageNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cpu_CpuUsageNative
 * Method:    getCpuUsage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_cpu_CpuUsageNative_getCpuUsage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
